### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by WNC12k**

### CODE REVIEW

**Comment by FoxMcloud5655** [comment]
Was this a mistake?

**Comment by WNC12k** [comment]
Yes, I accidentally chose the wrong branch

However, if there is a desire. We can connect the branches.

**Comment by FoxMcloud5655** [comment]
While I'd personally love to go over and see/test for the major changes, I am not the owner.  Not even sure if Sumwunn has this project's rework in their radar anymore.

**Comment by Sumwunn** [comment]
Still on my radar; trying multiple approaches to converting DRPG to ZScript, but having difficulties. Want to try to convert chunks of performance heavy and memory sensitive areas for performance and stability.

I'm 100% with WNC12k's balance changes, but do not like that it includes modified files from other mods (I do agree with the changes to them, though).

**Comment by FoxMcloud5655** [comment]
If you're fine with it, then that makes me want to look them over myself.

I have a completely custom build I've made that works with (or without) a custom mod that I've been developing with the help of FalcoLombardi5655 over the course of about 10 years.  I've been waiting for the rework into ZScript to port my changes over before trying to submit a pull request and integrate just the addition of our mod minus the reworked skills and balance changes I've made.

**Pull request closed without merging**
